Python Sets & Dictionaries( Concepts )
SETS : Unordered, mutable collections of unique elements.

Common Operations: add(), remove(), discard(), clear()

Set math:
union(), intersection(), difference(), symmetric_difference()
Operators: |, &, -, ^

📌 Use-Cases:
-Membership testing (if x in my_set) – super fast!
-Eliminating duplicates: set(my_list)
-Comparing datasets: e.g., shared users, missing IDs
-Efficient lookups in algorithms (e.g., visited nodes in graphs)



In [ ]:
# Real-World Example:
# Finding users who logged in both today and yesterday
logged_in_today = {'alice', 'bob', 'carol'}
logged_in_yesterday = {'bob', 'carol', 'dave'}

repeat_users = logged_in_today & logged_in_yesterday  # & = intersection
print(repeat_users)  # {'bob', 'carol'}





Python Dictionaries:
-Key-value pairs, mutable, unordered (in <3.7)
-Keys must be hashable (immutable types like strings, numbers, tuples)

Common Operations:
Access: my_dict[key] or .get(key, default)
Update: my_dict[key] = value
Remove: pop(key), del, popitem()
Iterate: items(), keys(), values()

 Use--Cases:
-Storing structured data: records, configs
-Lookup tables: maps, translations
-Counting: with collections.Counter
Nested data: JSON-like structures

In [ ]:
# Real-World Example:
# Handling JSON-like API response
user = {
    "id": 123,
    "name": "Alice",
    "roles": ["admin", "editor"],
    "location": {"city": "New York", "zip": "10001"}
}

print(user["location"]["city"])  # New York, 

roles = user["roles"]
print(roles)  # Output: ['admin', 'editor']

role_string = ", ".join(user["roles"])  ##", ".join(...) combines the list into a single string separated by commas
print(role_string)  # Output: admin, editor  



Exception Handling in Python**
  - try / except / else / finally

try:
    # Code that may raise an exception
except SomeException as e:
    # Handle the exception
else:
    # Executes *if no exception* was raised
finally:
    # Always executes, exception or not


In [ ]:
## Example 
def divide(a, b):
    try:
        result = a / b
    except ZeroDivisionError as e:
        print("Can't divide by zero!")
    else:
        print("Division successful:", result)
    finally:
        print("Operation complete.")

divide(10, 2)
divide(10, 0)


-----Raising Custom Exceptions----
- Using raise
- Creating Custom Exception Classes
- Using Custom Exception

In [24]:
## raise 
def set_age(age):
    if age < 0:
        #  Raise a built-in ValueError if age is invalid
        raise ValueError("Age cannot be negative.")
    # This runs if age is valid
    else:
        print("Age set to", age)
    
print(set_age(18))


Age set to 18
None


In [32]:

# ✅ Create your own exception by inheriting from Exception


def set_age(age):
    if age < 0:
        # ❌ Now raise your custom error instead of a built-in one
        raise InvalidAgeError("Age must be non-negative.")
    
    print(f"Age set to {age}")
    
print(set_age(31))

Age set to 31
None


In [28]:
#  Example:-----------
def divide(a, b):
    try:
        result = a / b
    except ZeroDivisionError as e: # ZeroDivisionRraised automatically by Python when you try to divide a number by zero.
        print("Can't divide by zero!")
    else:
        print("Division successful:", result)
    finally:
        print("Operation complete.")

divide(10, 2)
divide(10, 0)


Division successful: 5.0
Operation complete.
Can't divide by zero!
Operation complete.


In [33]:
try:
    set_age(-5)  # ❌ This will raise InvalidAgeError
except InvalidAgeError as e:
    # 🛑 Catch and handle your custom exception
    print("Custom Exception:", e)


Custom Exception: Age must be non-negative.


In [ ]:
**NumPy Basics**
Arrays vs Lists — Key Differences

Python arrays are similar to lists but are more efficient and suitable for numerical operations. 
They are part of the NumPy library, which provides support for large, multi-dimensional arrays and matrices, 
along with a large collection of high-level mathematical functions to operate on these arrays.

Feature	Python              List	                               NumPy Array (ndarray)
Heterogeneous?	            ✅ Yes	                               ❌ No (same data type only)
Faster?	                    ❌ No	                               ✅ Yes (C-optimized)
Supports math ops?	        ❌ No ([1,2]+[3,4] = [1,2,3,4])	   ✅ Yes (np.array([1,2]) + np.array([3,4]) = [4,6])
Memory Efficient?	        ❌ No	                               ✅ Yes



In [42]:
## CREATING ARRAYS
import numpy as np

# From list
a = np.array([1, 2, 3])           # 1D array
b = np.array([[1, 2], [3, 4]])    # 2D array

# With functions
zeros = np.zeros((2, 3))          # 2x3 array of zeros
ones = np.ones(5)                 # 1D array of ones
range_array = np.arange(0, 10, 2) # [0, 2, 4, 6, 8]
linspace_array = np.linspace(0, 1, 5) # 5 evenly spaced values between 0 and 1


print(a)
print(b)
print("-----------------------------------------------------------------------------------------")
print(zeros)
print("-----------------------------------------------------------------------------------------")
print(ones)
print("-----------------------------------------------------------------------------------------")
print(range_array)
print("-----------------------------------------------------------------------------------------")
print(linspace_array)

[1 2 3]
[[1 2]
 [3 4]]
-----------------------------------------------------------------------------------------
[[0. 0. 0.]
 [0. 0. 0.]]
-----------------------------------------------------------------------------------------
[1. 1. 1. 1. 1.]
-----------------------------------------------------------------------------------------
[0 2 4 6 8]
-----------------------------------------------------------------------------------------
[0.   0.25 0.5  0.75 1.  ]


In [43]:
## Array Operations

arr = np.array([1, 2, 3])

# Element-wise math
print(arr + 5)        # [6 7 8]
print(arr * 2)        # [2 4 6]
print(arr ** 2)       # [1 4 9]

# Aggregate functions
print(arr.sum())      # 6
print(arr.mean())     # 2.0
print(arr.max())      # 3


[6 7 8]
[2 4 6]
[1 4 9]
6
2.0
3


In [ ]:
##Broadcasting (🔥 Powerful feature)
#  Broadcasting = automatic resizing during operations (when dimensions don't match but are compatible).

a = np.array([1, 2, 3])
b = 2
print(a + b)  # [3 4 5] — b is "broadcasted" to match `a`

# 2D + 1D broadcast
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([10, 20, 30])
print(A + B)
# Output:
# [[11 22 33]
#  [14 25 36]]


TL;DR Summary:
🔥Use np.array() for fast math, memory efficiency, and matrix-style ops

🔥Think in vectors & matrices — slicing, indexing, broadcasting are key!

🔥Python lists are flexible but NumPy arrays are optimized for speed + numerical work

🔁 Practice Tasks
- Create a function using `try/except` to divide numbers with error handling
- Create a dictionary-based student record system (search, insert, update)
- Convert a list into a NumPy array and perform basic math operations
- Compare speed of NumPy array ops vs native Python loops

In [46]:
#1. Function with try/except for Safe Division
def safe_divide(a, b):
    try:
        result = a / b
    except ZeroDivisionError:
        return "Error: Cannot divide by zero"
    except TypeError: #A TypeError in Python occurs when you try to perform an operation on an object of an incorrect type.
        return "Error: Inputs must be numbers"
    else:
        return f"Result: {result}"
    finally:
        print("Division attempt finished.")

# Test cases
print(safe_divide(10, 2))   # Result: 5.0
print("-----------------------------------------------------------------------------------------")
print(safe_divide(10, 0))   # Error: Cannot divide by zero
print("-----------------------------------------------------------------------------------------")
print(safe_divide(10, 'a')) # Error: Inputs must be numbers



Division attempt finished.
Result: 5.0
-----------------------------------------------------------------------------------------
Division attempt finished.
Error: Cannot divide by zero
-----------------------------------------------------------------------------------------
Division attempt finished.
Error: Inputs must be numbers


In [47]:
#2. Dictionary-Based Student Record System
students = {}

def insert_student(student_id, name, grade):
    students[student_id] = {"name": name, "grade": grade}

def update_student(student_id, name=None, grade=None):
    if student_id in students:
        if name:
            students[student_id]["name"] = name
        if grade:
            students[student_id]["grade"] = grade
    else:
        print("Student not found.")

def search_student(student_id):
    return students.get(student_id, "Student not found.")

# Example usage
insert_student(101, "Alice", 88)
insert_student(102, "Bob", 75)
update_student(101, grade=90)
print(students)
print(search_student(101))  # {'name': 'Alice', 'grade': 90}
print(search_student(999))  # Student not found.


{101: {'name': 'Alice', 'grade': 90}, 102: {'name': 'Bob', 'grade': 75}}
{'name': 'Alice', 'grade': 90}
Student not found.


In [49]:
## 3. Convert List to NumPy Array + Math Ops

import numpy as np

my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)

# Basic operations
print(arr + 10)   # [11 12 13 14 15]
print(arr * 2)    # [2 4 6 8 10]
print(arr.mean()) # 3.0
print(arr ** 2)   # [ 1  4  9 16 25]



[11 12 13 14 15]
[ 2  4  6  8 10]
3.0
[ 1  4  9 16 25]


In [50]:
## 4. Speed Comparison: NumPy vs Native Python

import numpy as np      # Import NumPy for fast array operations
import time             # Import time to measure execution speed

# Step 1: Create a large dataset with 1 million numbers
size = 1_000_000  # Underscores just improve readability: same as 1000000

# Native Python list
py_list = list(range(size))   # [0, 1, 2, ..., 999999]

# NumPy array version of the same data
np_array = np.array(py_list) # Faster, optimized array


# Part 1: Python list operation (using list comprehension)---------------------------------------------
start = time.time()  # Record the start time
py_result = [x * 2 for x in py_list]  # Multiply each element by 2 (slow loop)

end = time.time()  # Record the end time
print(f"Python list time: {end - start:.5f} seconds")  # Print time taken


# Part 2: NumPy vectorized operation--------------------------------------------------------------------
start = time.time()  # Record start again for NumPy

np_result = np_array * 2  # Fast vectorized multiplication

end = time.time()  # Record end time
print(f"NumPy array time: {end - start:.5f} seconds")  # Print time taken


Python list time: 0.05654 seconds
NumPy array time: 0.00276 seconds


Build a mini CLI program to:
  - Store and retrieve info using a dictionary
  - Handle user input safely using exception handling
  - Use NumPy for any number-based calculations



✅ Goals:
-📁 Store student data in a dictionary (name → marks)
-💬 User can insert, search, or update marks
-🔐 Handle input safely with try/except
-🧮 Use NumPy to compute stats (mean, max, min, etc.) on all marks



In [ ]:
## a mini CLI (Command-Line Interface) program for student data handling.


import numpy as np

studentrecord = {}

def add_or_update():
    name = input("Enter students name").strip()

    try:
        marks= float(input("Enter overall percentage(0-100)"))
        if not ( 0 <= marks <= 100):
                     raise ValueError("Percentage must be between 0 and 100.")
        studentrecord[name] = marks
        print("✅ Record saved for", name, ".")
    except ValueError as ve:
        print("❌ Invalid input:", ve )
          
# 🔍 Function to search for a student
def search():
    name = input("Enter student name to search: ").strip()
    if name in studentrecord:
        print(name,'s marks:', studentrecord[name],"%")
    else:
        print("⚠️ Student not found.")
        

# 📊 Function to show statistics using NumPy
def show_stats():
     if not studentrecord:
         print("Nothing to analyze.")
         return
         
     # Get all marks as a NumPy array
     marks_array = np.array(list(studentrecord.values()))

     # Basic stats
     print("📊 Students Statistics:")
     print("Mean:", {marks_array.mean()})
     print("Min:", {marks_array.min()})
     print("Max:", {marks_array.max()})
     print("Std_dev:", {marks_array.std()})
    
# 🧩 Menu Loop
def main():
    while True:
        print("\n=== Student Record CLI ===")
        print("1. Add/Update Student")
        print("2. Search Student")
        print("3. Show Overall Statistics")
        print("4. Exit")

    
        try:
            choice = int(input("Choose an option (1-4): "))
        except ValueError:
            print("❌ Please enter a number (1-4).")
            continue  # Ask again

        if choice == 1:
            add_or_update()
        elif choice == 2:
            search()
        elif choice == 3:
            show_stats()
        elif choice == 4:
            print("👋 Exiting program. Goodbye!")
            break

        else:
            print("❌ Invalid option. Please try again.")

# 🔁 Run the menu
main()






















=== Student Record CLI ===
1. Add/Update Student
2. Search Student
3. Show Overall Statistics
4. Exit


Choose an option (1-4):  1
Enter students name Harshit
Enter overall percentage(0-100) 100


✅ Record saved for Harshit .

=== Student Record CLI ===
1. Add/Update Student
2. Search Student
3. Show Overall Statistics
4. Exit


Choose an option (1-4):  2
Enter student name to search:  Harshit


Harshit s marks: 100.0 %

=== Student Record CLI ===
1. Add/Update Student
2. Search Student
3. Show Overall Statistics
4. Exit


@ LEARNINGS
Concept	                              Implementation
Dictionary storage	                  student_records = {name: marks}
Safe input handling	                  try/except with ValueError
NumPy usage	                          np.array([...]) to calculate mean, max, min, std
CLI interaction	                      input(), while True, numbered menu